language: php

branches:
  only:
    - master

cache:
  directories:
  - vendor
  - venv

before_install: ./.travis/before_install.php
install: ./.travis/install.php
script: ./.travis/script.php

matrix:
  include:
    # old PHP versions with latest Symfony version
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.1
      env: SYMFONY_VERSION=dev-master
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
